spring.application.name=orderService

server.port=8083

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
management.endpoints.web.exposure.include=*

resilience4j.circuitbreaker.instances.moviedetailservice.registerHealthIndicator=true

resilience4j.circuitbreaker.instances.moviedetailservice.slidingWindowSize=10

resilience4j.circuitbreaker.instances.moviedetailservice.minimumNumberOfCalls=5

resilience4j.circuitbreaker.instances.moviedetailservice.failureRateThreshold=50

resilience4j.circuitbreaker.instances.moviedetailservice.waitDurationInOpenState=10s

resilience4j.circuitbreaker.instances.moviedetailservice.permittedNumberOfCallsInHalfOpenState=3

resilience4j.circuitbreaker.instances.moviedetailservice.eventConsumerBufferSize=10

resilience4j.circuitbreaker.instances.moviedetailservice.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.moviedetailservice.sliding-window-type=COUNT_BASED

spring.datasource.url=jdbc:postgresql://localhost:5432/EMPLOYEE
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
